name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.2.6

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0 # use the latest version compatible with your project
  file_picker: ^6.1.1 # Use the latest version of file_picker
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/notAI3.png